# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  hyprnote = {
    pname = "hyprnote";
    version = "1.0.0-nightly.21";
    src = fetchurl {
      url = "https://github.com/fastrepl/hyprnote/releases/download/desktop_v1.0.0-nightly.21/hyprnote-linux-x86_64.AppImage";
      sha256 = "sha256-cuv3e/BMIW2YimPnV2LAGdv7i7+rXhJJGXjAQG+su/c=";
    };
  };
}
